# Kristhy Medical - Multi-Stage Dockerfile
# Optimized for Next.js 16 + pnpm 10.17.1 + Prisma 7
# Target image size: ~350-400MB

# ============================================
# Stage 1: Base - Node.js 20 Alpine with pnpm
# ============================================
FROM node:20-alpine AS base

# Enable corepack for pnpm
RUN corepack enable && corepack prepare pnpm@10.17.1 --activate

# Install OpenSSL and other dependencies required by Prisma
RUN apk add --no-cache \
    libc6-compat \
    openssl

WORKDIR /app

# ============================================
# Stage 2: Dependencies - Install packages
# ============================================
FROM base AS deps

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies with frozen lockfile (reproducible builds)
RUN pnpm install --frozen-lockfile --prod=false

# ============================================
# Stage 3: Builder - Generate Prisma client and build Next.js
# ============================================
FROM base AS builder

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy application source
COPY . .

# Build argument for DATABASE_URL (required by Prisma and Next.js build)
ARG DATABASE_URL="postgresql://user:pass@localhost:5432/db?pgbouncer=true"
ARG DIRECT_URL="postgresql://user:pass@localhost:5432/db"

# Set as environment variables for build
ENV DATABASE_URL=$DATABASE_URL
ENV DIRECT_URL=$DIRECT_URL
ENV NEXT_TELEMETRY_DISABLED=1

# Generate Prisma Client
RUN pnpm prisma generate

# Create .env.production for Next.js build (ensures env vars are available to workers)
RUN printf "DATABASE_URL=%s\nDIRECT_URL=%s\n" "$DATABASE_URL" "$DIRECT_URL" > .env.production

# Build Next.js application with standalone output
# This generates a minimal production bundle in .next/standalone
RUN pnpm next build

# ============================================
# Stage 4: Runner - Production image
# ============================================
FROM base AS runner

WORKDIR /app

# Set production environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=builder /app/public ./public

# Copy Prisma schema and migrations (needed for runtime)
COPY --from=builder /app/prisma ./prisma

# Copy Prisma Client (generated in builder stage)
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Copy standalone Next.js output
# This includes only the necessary files for production
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

# Expose port 3000
EXPOSE 3000

# Set port environment variable
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Health check
# Checks /api/health endpoint every 30 seconds
# Waits 30 seconds before first check to allow app to start
# Times out after 10 seconds
# Retries 3 times before marking unhealthy
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start the application
# The standalone server.js is generated by Next.js
CMD ["node", "server.js"]
